package hu.me.utils;

public enum ErrorMessage {
    VALID,
    EMPTYCHECKERARRAY,
    USERNAMETOOSHORT,
    PASSWORDTOOSHORT,
    USERNAMECONTAINSWHITESPACE,
    PASSWORDCONTAINSWHITESPACE,
    USERNAMEISNULL,
    PASSWORDISNULL
}
